CREATE TABLE Libros(
    ISBN DECIMAL(13, 0) PRIMARY KEY,
    Título VARCHAR(50) UNIQUE NOT NULL,
    Autor VARCHAR(30),
    Género VARCHAR(10),
    Año Decimal(5, 0),
    FOREIGN KEY (Autor) REFERENCES Autores(Nombre)
    ON UPDATE CASCADE
);

CREATE TABLE Autores(
    ID_autor INT PRIMARY KEY AUTO_INCREMENT,
    Nombre VARCHAR(30) NOT NULL UNIQUE,
    Nacionalidad VARCHAR(20) NOT NULL
);

CREATE TABLE Socios(
    DNI DECIMAL(8, 2) PRIMARY KEY,
    Nombre VARCHAR(30) NOT NULL,
    Teléfono DECIMA(9, 0) UNIQUE,
    Fecha DATE DEFAULT CURRENT_DATE()
);

CREATE TABLE Prestamos(
    ID_prestamos INT PRIMARY KEY AUTO_INCREMENT,
    ISBN DECIMAL(13, 0),
    DNI DECIMAL(8, 2),
    FechaPrestamo DATE DEFAULT CURRENT_DATE,
    FechaDevolución DATE NULL,
    FOREIGN KEY (ISBN) REFERENCES Libros(ISBN)
    ON UPDATE CASCADE,
    FOREIGN KEY (DNI) REFERENCES Socios(DNI)
    ON UPDATE CASCADE
);